import { pgTable, text, timestamp, integer, boolean, uuid, index } from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'

// Better Auth tables (generated by better-auth CLI)
export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').default(false).notNull(),
  image: text('image'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().$onUpdate(() => new Date()).notNull(),
})

export const session = pgTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: timestamp('expires_at').notNull(),
    token: text('token').notNull().unique(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()).notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  },
  (table) => [index('session_userId_idx').on(table.userId)],
)

export const account = pgTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at'),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
    scope: text('scope'),
    password: text('password'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').$onUpdate(() => new Date()).notNull(),
  },
  (table) => [index('account_userId_idx').on(table.userId)],
)

export const verification = pgTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at').notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().$onUpdate(() => new Date()).notNull(),
  },
  (table) => [index('verification_identifier_idx').on(table.identifier)],
)

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}))

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}))

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}))

// Domain tables
export const profile = pgTable('profile', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }).unique(),
  fullName: text('full_name').notNull().default(''),
  role: text('role').notNull().default('Full-Stack Developer'),
  shortBio: text('short_bio').notNull().default(''),
  longBio: text('long_bio').notNull().default(''),
  email: text('email').notNull().default(''),
  location: text('location').notNull().default(''),
  resumeUrl: text('resume_url'),
  resumePublicId: text('resume_public_id'),
  avatarUrl: text('avatar_url'),
  avatarPublicId: text('avatar_public_id'),
  githubUrl: text('github_url').notNull().default(''),
  linkedinUrl: text('linkedin_url').notNull().default(''),
  twitterUrl: text('twitter_url').notNull().default(''),
  websiteUrl: text('website_url').notNull().default(''),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const projects = pgTable('projects', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: text('title').notNull(),
  slug: text('slug').notNull().unique(),
  shortDescription: text('short_description').notNull().default(''),
  longDescription: text('long_description').notNull().default(''),
  howItWasBuilt: text('how_it_was_built').notNull().default(''),
  techStack: text('tech_stack').array().notNull().default([]),
  tags: text('tags').array().notNull().default([]),
  thumbnailUrl: text('thumbnail_url'),
  thumbnailPublicId: text('thumbnail_public_id'),
  liveUrl: text('live_url').notNull().default(''),
  demoUrl: text('demo_url').notNull().default(''),
  githubUrl: text('github_url').notNull().default(''),
  isPublished: boolean('is_published').notNull().default(true),
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})

export const projectImages = pgTable('project_images', {
  id: uuid('id').primaryKey().defaultRandom(),
  projectId: uuid('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
  url: text('url').notNull(),
  publicId: text('public_id').notNull(),
  altText: text('alt_text').notNull().default(''),
  caption: text('caption').notNull().default(''),
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: timestamp('created_at').notNull().defaultNow(),
})

export const skills = pgTable('skills', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  category: text('category').notNull().default('General'),
  proficiency: integer('proficiency').notNull().default(3),
  iconUrl: text('icon_url'),
  sortOrder: integer('sort_order').notNull().default(0),
})

export const experiences = pgTable('experiences', {
  id: uuid('id').primaryKey().defaultRandom(),
  role: text('role').notNull(),
  company: text('company').notNull().default(''),
  description: text('description').notNull().default(''),
  startDate: text('start_date').notNull(),
  endDate: text('end_date'),
  isCurrentRole: boolean('is_current_role').notNull().default(false),
  sortOrder: integer('sort_order').notNull().default(0),
})

export const resumeContent = pgTable('resume_content', {
  id: uuid('id').primaryKey().defaultRandom(),
  sectionTitle: text('section_title').notNull(),
  content: text('content').notNull().default(''),
  sortOrder: integer('sort_order').notNull().default(0),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
})
