/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminSkillsRouteImport } from './routes/admin/skills'
import { Route as AdminResumeRouteImport } from './routes/admin/resume'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminExperiencesRouteImport } from './routes/admin/experiences'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as PublicResumeIndexRouteImport } from './routes/_public/resume/index'
import { Route as PublicProjectsIndexRouteImport } from './routes/_public/projects/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminProjectsNewRouteImport } from './routes/admin/projects/new'
import { Route as AdminProjectsIdRouteImport } from './routes/admin/projects/$id'
import { Route as PublicResumePdfRouteImport } from './routes/_public/resume/pdf'
import { Route as PublicProjectsSlugRouteImport } from './routes/_public/projects/$slug'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResumeRoute = AdminResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExperiencesRoute = AdminExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => AdminRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicResumeIndexRoute = PublicResumeIndexRouteImport.update({
  id: '/resume/',
  path: '/resume/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProjectsIndexRoute = PublicProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsIdRoute = AdminProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AdminRoute,
} as any)
const PublicResumePdfRoute = PublicResumePdfRouteImport.update({
  id: '/resume/pdf',
  path: '/resume/pdf',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProjectsSlugRoute = PublicProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/resume': typeof AdminResumeRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/$slug': typeof PublicProjectsSlugRoute
  '/resume/pdf': typeof PublicResumePdfRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/': typeof PublicProjectsIndexRoute
  '/resume/': typeof PublicResumeIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/resume': typeof AdminResumeRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/projects/$slug': typeof PublicProjectsSlugRoute
  '/resume/pdf': typeof PublicResumePdfRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects': typeof PublicProjectsIndexRoute
  '/resume': typeof PublicResumeIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/admin/experiences': typeof AdminExperiencesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/resume': typeof AdminResumeRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/projects/$slug': typeof PublicProjectsSlugRoute
  '/_public/resume/pdf': typeof PublicResumePdfRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_public/projects/': typeof PublicProjectsIndexRoute
  '/_public/resume/': typeof PublicResumeIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/setup'
    | '/about'
    | '/contact'
    | '/admin/experiences'
    | '/admin/profile'
    | '/admin/resume'
    | '/admin/skills'
    | '/admin/'
    | '/projects/$slug'
    | '/resume/pdf'
    | '/admin/projects/$id'
    | '/admin/projects/new'
    | '/api/auth/$'
    | '/projects/'
    | '/resume/'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/about'
    | '/contact'
    | '/admin/experiences'
    | '/admin/profile'
    | '/admin/resume'
    | '/admin/skills'
    | '/'
    | '/admin'
    | '/projects/$slug'
    | '/resume/pdf'
    | '/admin/projects/$id'
    | '/admin/projects/new'
    | '/api/auth/$'
    | '/projects'
    | '/resume'
    | '/admin/projects'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/login'
    | '/setup'
    | '/_public/about'
    | '/_public/contact'
    | '/admin/experiences'
    | '/admin/profile'
    | '/admin/resume'
    | '/admin/skills'
    | '/_public/'
    | '/admin/'
    | '/_public/projects/$slug'
    | '/_public/resume/pdf'
    | '/admin/projects/$id'
    | '/admin/projects/new'
    | '/api/auth/$'
    | '/_public/projects/'
    | '/_public/resume/'
    | '/admin/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/skills': {
      id: '/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resume': {
      id: '/admin/resume'
      path: '/resume'
      fullPath: '/admin/resume'
      preLoaderRoute: typeof AdminResumeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experiences': {
      id: '/admin/experiences'
      path: '/experiences'
      fullPath: '/admin/experiences'
      preLoaderRoute: typeof AdminExperiencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/resume/': {
      id: '/_public/resume/'
      path: '/resume'
      fullPath: '/resume/'
      preLoaderRoute: typeof PublicResumeIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/projects/': {
      id: '/_public/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof PublicProjectsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/$id': {
      id: '/admin/projects/$id'
      path: '/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AdminProjectsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/resume/pdf': {
      id: '/_public/resume/pdf'
      path: '/resume/pdf'
      fullPath: '/resume/pdf'
      preLoaderRoute: typeof PublicResumePdfRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/projects/$slug': {
      id: '/_public/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof PublicProjectsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicProjectsSlugRoute: typeof PublicProjectsSlugRoute
  PublicResumePdfRoute: typeof PublicResumePdfRoute
  PublicProjectsIndexRoute: typeof PublicProjectsIndexRoute
  PublicResumeIndexRoute: typeof PublicResumeIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicProjectsSlugRoute: PublicProjectsSlugRoute,
  PublicResumePdfRoute: PublicResumePdfRoute,
  PublicProjectsIndexRoute: PublicProjectsIndexRoute,
  PublicResumeIndexRoute: PublicResumeIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminExperiencesRoute: typeof AdminExperiencesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminResumeRoute: typeof AdminResumeRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProjectsIdRoute: typeof AdminProjectsIdRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminExperiencesRoute: AdminExperiencesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminResumeRoute: AdminResumeRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProjectsIdRoute: AdminProjectsIdRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
